---
nsq_namespace: "metal-stack-cloud"


nsqd_address: nsqd:4150

nsq_set_resource_limits: true
nsq_nsqd_resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "1"
nsq_nsq_lookupd_resources:
  requests:
    memory: "8Mi"
    cpu: "20m"
  limits:
    memory: "100Mi"
    cpu: "1"

nsq_log_level: info
nsq_nsqd_data_size: 100Mi

nsq_image_pull_policy: IfNotPresent
