---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reporter-config
data:
  config.yaml: |
    {{ lookup('template', 'accounting-config.yaml') | indent(width=4, first=false) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: reporter-masterdata-api-certs
type: Opaque
stringData:
  ca.pem: |
    {{ accounting_masterdata_api_ca | indent(width=4, first=false) }}
  cert.pem: |
    {{ accounting_masterdata_api_cert | indent(width=4, first=false) }}
  cert-key.pem: |
    {{ accounting_masterdata_api_cert_key | indent(width=4, first=false) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounting-reporter
  name: accounting-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-reporter
  template:
    metadata:
      labels:
        app: accounting-reporter
      annotations:
        checksum/config: "{{ lookup('template', 'accounting-config.yaml') | string | hash('sha1') }}"
    spec:
      containers:
      - image: {{ metal_stack_cloud_accounting_reporter_image_name }}:{{ metal_stack_cloud_accounting_reporter_image_tag }}
        name: reporter
        args:
        - --config=/etc/accounting/reporter/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/accounting/reporter/
        - name: masterdata-api-certs
          mountPath: /certs/masterdata-api/
      volumes:
        - name: config
          configMap:
            name: reporter-config
        - name: masterdata-api-certs
          secret:
            secretName: reporter-masterdata-api-certs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sender-config
data:
  config.yaml: |
    stripe-account-token: {{ accounting_stripe_private_token }}
    nsqd-addr: {{ accounting_nsqd_address }}
    log-level: {{ accounting_log_level }}
    log-only: {{ accounting_log_only | lower }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounting-sender
  name: accounting-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-sender
  template:
    metadata:
      labels:
        app: accounting-sender
    spec:
      containers:
      - image: {{ metal_stack_cloud_accounting_sender_image_name }}:{{ metal_stack_cloud_accounting_sender_image_tag }}
        name: sender
        args:
        - --config=/etc/accounting/sender/config.yaml
        ports:
        - containerPort: 2112
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/accounting/sender/
      volumes:
        - name: config
          configMap:
            name: sender-config
---
apiVersion: v1
kind: Service
metadata:
  name: accounting-sender
  labels:
    app: accounting-sender
spec:
  selector:
    app: accounting-sender
  ports:
  - name: metrics
    port: 2112
    targetPort: 2112
