server-url: {{ status_server_url }}
grpc-server-ca-path: /certs/ca.pem
grpc-server-cert-path: /certs/server.pem
grpc-server-key-path: /certs/server-key.pem
api-endpoint: {{ status_api_url }}
api-token: {{ status_api_token }}
{% if status_api_ca_cert %}
api-ca-file: /certs/api-ca.pem
{% endif %}
log-level: {{ status_log_level }}
chat-channel-id: {{ status_chat_channel_id }}
chat-token: {{ status_chat_token }}
{% if status_schedule is not none %}
schedule: {{ status_schedule }}
{% endif %}
