---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nsqd
  name: nsqd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsqd
  serviceName: nsqd
  template:
    metadata:
      labels:
        app: nsqd
    spec:
      containers:
      - name: nsqd
        args:
        - /nsqd
        - -log-level={{ api_server_nsq_log_level }}
        - -data-path=/data
        image: {{ metal_stack_cloud_nsq_image_name }}:{{ metal_stack_cloud_nsq_image_tag }}
        imagePullPolicy: {{ api_server_nsq_image_pull_policy }}
        ports:
        - containerPort: 4150
        - containerPort: 4151
{% if api_server_nsq_set_resource_limits %}
        resources: {{ api_server_nsq_nsqd_resources | to_json }}
{% endif %}
        volumeMounts:
        - name: nsqd
          mountPath: /data
      - name: nsq-admin
        image: {{ metal_stack_cloud_nsq_image_name }}:{{ metal_stack_cloud_nsq_image_tag }}
        imagePullPolicy: {{ api_server_nsq_image_pull_policy }}
        ports:
        - containerPort: 4171
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
        args:
          - /nsqadmin
          - -log-level={{ api_server_nsq_log_level }}
          - --nsqd-http-address=localhost:4151
      volumes:
      - name: nsqd
        persistentVolumeClaim:
          claimName: nsqd
  volumeClaimTemplates:
  - metadata:
      name: nsqd
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ api_server_nsq_nsqd_data_size }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsqd
  name: nsqd
spec:
  ports:
  - name: "4150"
    port: 4150
    targetPort: 4150
  - name: "4151"
    port: 4151
    targetPort: 4151
  - name: "4171"
    port: 4171
    targetPort: 4171
  selector:
    app: nsqd
