nsqd-addr: {{ api_server_nsqd_address }}
nsqd-topic: {{ api_server_nsqd_topic }}
log-level: {{ api_server_sender_log_level }}
log-only: {{ api_server_sender_log_only }}
smtp-from-address: {{ api_server_sender_mail_smtp_from_address }}
smtp-from-name: {{ api_server_sender_mail_smtp_from_name }}
mail-provider: {{ api_server_sender_mail_provider }}
mail-config-path: {{ api_server_sender_mail_config_path }}
auditing-url: {{ api_server_auditing_url }}
auditing-api-key: {{ api_server_auditing_key }}
auditing-enabled: {{ api_server_auditing_enabled }}
auditing-index-prefix: {{ api_server_auditing_index_prefix }}
auditing-index-interval: "daily"
auditing-index-keep: {{ api_server_auditing_keep }}
