---
masterdata:
  ca: |
    {{ api_server_masterdata_api_ca | indent(width=4, first=false) }}
  cert: |
    {{ api_server_masterdata_api_cert | indent(width=4, first=false) }}
  certKey: |
    {{ api_server_masterdata_api_cert_key | indent(width=4, first=false) }}
  hostname: "{{ api_server_masterdata_api_hostname }}"
  port: "{{ api_server_masterdata_api_port }}"
  hmac: "{{ api_server_masterdata_api_hmac }}"

auditing:
  url: "{{ api_server_auditing_url }}"
  key: "{{ api_server_auditing_key }}"

metal:
  url: "{{ api_server_metal_api_url }}"
  hmac: "{{ api_server_metal_api_hmac }}"

frontend:
  url: "{{ api_server_frontend_url }}"

api:
  url: "{{ api_server_http_url }}"
  logLevel: "{{ api_server_log_level }}"
  replicas: "{{ api_server_replicas }}"
  sessionSecret: "{{ api_server_session_secret }}"
  jwtTokenSecret: "{{ api_server_jwt_token_secret }}"
  image:
    name: "{{ metal_stack_cloud_api_server_image_name }}"
    tag: "{{ metal_stack_cloud_api_server_image_tag }}"
{% if api_server_tls_ca %}
  ca: |
    {{ api_server_tls_ca | indent(width=4, first=false) }}
{% endif %}
{% if api_server_tls_cert %}
  cert: |
    {{ api_server_tls_cert | indent(width=4, first=false) }}
{% endif %}
{% if api_server_tls_cert_key %}
  certKey: |
    {{ api_server_tls_cert_key | indent(width=4, first=false) }}
{% endif %}

{% if api_server_resources %}
  resources: {{ api_server_resources | to_json }}
{% endif %}

  podDisruptionBudget:
    enabled: {{ api_server_pdb_enabled }}
    minAvailable: {{ api_server_pdb_min_available }}

  hpa:
    enabled: {{ api_server_hpa_enabled }}
    maxReplicas: {{ api_server_hpa_max }}
    minReplicas: {{ api_server_hpa_min }}
    cpuPercentage: {{ api_server_hpa_cpu_percentage }}

  github:
    clientID: "{{ api_server_github_client_id }}"
    clientSecret: "{{ api_server_github_client_secret }}"
  azure:
    applicationID: "{{ api_server_azure_application_id }}"
    clientSecret: "{{ api_server_azure_client_secret }}"

  stripe:
    secretKey: "{{ api_server_stripe_secret_key }}"
    configYaml: |
      {{ api_server_stripe_config | indent(width=6, first=false) }}

gardener:
  kubeconfig: |
    {{ api_server_gardener_kubeconfig | indent(width=4, first=false) }}

ingress:
  authHost: "{{ api_server_ingress_dns_auth }}"
  grpcHost: "{{ api_server_ingress_dns_grpc }}"
  grpcWebHost: "{{ api_server_ingress_dns_web_grpc }}"
{% if api_server_ingress_annotations %}
  annotations: {{ api_server_ingress_annotations | to_json }}
{% endif %}
  tls:
    enabled: {{ api_server_ingress_tls_enabled }}
