---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  config.js: |
    window.API_URL = "{{ console_api_url }}"
    window.AUTH_CALLBACK = "{{ console_api_auth_callback_url }}"
    window.STRIPE_PUBLIC_KEY = "{{ console_stripe_public_key }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
spec:
  replicas: {{ console_replicas }}
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - image: {{ metal_stack_cloud_console_image_name }}:{{ metal_stack_cloud_console_image_tag }}
        name: console
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
        - name: config
          configMap:
            name: console-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
spec:
  selector:
    app: console
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: console.172.17.0.1.nip.io
    http:
      paths:
      - backend:
          service:
            name: console
            port:
              number: 80
        path: /
        pathType: Prefix
