---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  config.js: |
    {{ lookup('template', 'console-config.yaml') | indent(width=4, first=false) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
spec:
  replicas: {{ console_replicas }}
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
      annotations:
        checksum/config: "{{ lookup('template', 'console-config.yaml') | string | hash('sha1') }}"
    spec:
      containers:
      - image: {{ metal_stack_cloud_console_image_name }}:{{ metal_stack_cloud_console_image_tag }}
        name: console
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
        - name: config
          configMap:
            name: console-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
spec:
  selector:
    app: console
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
  annotations: {{ console_ingress_annotations | to_json }}
spec:
  ingressClassName: nginx
{% if console_ingress_tls_enabled %}
  tls:
  - hosts:
    - {{ console_ingress_dns }}
    secretName: console-tls
{% endif %}
  rules:
  - host: {{ console_ingress_dns }}
    http:
      paths:
      - backend:
          service:
            name: console
            port:
              number: 80
        path: /
        pathType: Prefix
