---
masterdata:
  ca: |
    A certificate
    with multiple lines
  cert: |
    A certificate
    with multiple lines
  certKey: |
    A certificate
    with multiple lines
  hostname: mastedata
  port: 3000
  hmac: secret-hmac

gardener:
  kubeconfig: ""

auditing:
  url: auditing
  key: secret

metal:
  url: metal-api
  hmac: secret-hmac

frontend:
  url: localhost

api:
  url: localhost
  logLevel: info
  replicas: 2
  sessionSecret: secret
  jwtTokenSecret: geheim
  image:
    name: ghcr.io/metal-stack-cloud/api-server
    tag: latest

  ca:
  # ca: |
  #   A certificate
  #   with multiple lines

  # if not provided, it is expected that a secret with valid certs exist
  # in a secret called api-server-tls
  # (can also be deployed through cert-manager ingress annotation)
  cert:
  # cert: |
  #   A certificate
  #   with multiple lines
  certKey:
  # certKey: |
  #   A certificate
  #   with multiple lines

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  hpa:
    enabled: true
    maxReplicas: 5
    minReplicas: 2
    cpuPercentage:

  github:
    clientID: client-id
    clientSecret: client-secret
  azure:
    applicationID: app-id
    clientSecret: client-secret

  stripe:
    secretKey: stripe-secret
    configYaml: |
      products: []

  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2"

ingress:
  enabled: true
  className: nginx
  host: ""
  annotations: {}
  tls:
    enabled: false
