---
masterdata:
  ca: |
    A certificate
    with multiple lines
  cert: |
    A certificate
    with multiple lines
  certKey: |
    A certificate
    with multiple lines
  hostname: mastedata
  port: 3000
  hmac: secret-hmac

tokenStore:
  addr:
  password:

gardener:
  kubeconfig: ""

auditing:
  enabled: true
  host: auditing-timescaledb
  port: 5432
  db: auditing
  user: postgres
  password: "change-me"
  retention: "14-days"

metal:
  url: metal-api
  hmac: secret-hmac

frontend:
  url: localhost

api:
  url: localhost
  userAdmittance: true
  disableBilling: false
  logLevel: debug
  logOnly: false
  replicas: 1
  sessionSecret: secret
  adminSubjects: []
  image:
    name: ghcr.io/metal-stack-cloud/api-server
    tag: latest

  ca:
  # ca: |
  #   A certificate
  #   with multiple lines

  # if not provided, it is expected that a secret with valid certs exist
  # in a secret called api-server-tls
  # (can also be deployed through cert-manager ingress annotation)
  cert:
  # cert: |
  #   A certificate
  #   with multiple lines
  certKey:
  # certKey: |
  #   A certificate
  #   with multiple lines

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  hpa:
    enabled: true
    maxReplicas: 5
    minReplicas: 2
    cpuPercentage:

  github:
    clientID: client-id
    clientSecret: client-secret
  azure:
    applicationID: app-id
    clientSecret: client-secret
  google:
    applicationID: app-id
    clientSecret: client-secret

  stripe:
    secretKey: stripe-secret
    configYaml: |
      products: []

  rateLimit:
    maxRequestsPerMinute: 1000
    maxUnauthenticatedRequestsPerMinute: 50

  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2"

  duros:
    config:
      # ---
      # eqx-mu4:
      #   endpoints:
      #     - "1.2.3.4"
      #     - "1.2.3.5"
      #   admintoken: admin-jwt-token
      #   storageclasses:
      #     - name: standard
      #       replicas: 2
      #       compression: true

ingress:
  enabled: true
  className: nginx
  host: ""
  annotations: {}
  tls:
    enabled: false

mail:
  provider: none # none, mailjet
  smtpFromName: metalstack.cloud
  smtpFromAddress: info@x-cellent.com
  mailjet:
    apiKeyPublic: mj-api-key-public
    apiKeyPrivate: mj-api-key-private
    config:
      # mail_templates: # mapping of mail templates to mailjet template ids
      #   Welcome: 4712279
      #   Admitted: 4727583
      #   CouponPercentageUsedWarning: 4731146
      #   CouponCompletelyUsedWarning: 4731184
      #   PaymentUpdated: 4727758
