---
console_namespace: "{{ metal_stack_cloud_namespace }}"
console_replicas: 3

console_api_url: http://api.{{ metal_stack_cloud_ingress_dns }}
console_api_auth_callback_url: https://api.{{ metal_stack_cloud_ingress_dns }}/auth
console_stripe_public_key: "{{ metal_stack_cloud_stripe_public_token }}"
