---
console_namespace: "{{ metal_stack_cloud_namespace }}"
console_replicas: 3

console_api_url: https://api.{{ metal_stack_cloud_ingress_dns }}
console_api_auth_callback_url: https://api.{{ metal_stack_cloud_ingress_dns }}/auth
console_api_auth_test_callback_url: "{{ console_api_auth_callback_url }}/test/callback"
console_stripe_public_key: "{{ metal_stack_cloud_stripe_public_token }}"

console_open_auth_test: false
console_show_azure_login: false

console_debug_mode: true

console_email_consent: false

console_load_privacy_window: true

console_ingress_dns: console.{{ metal_stack_cloud_ingress_dns }}
console_ingress_tls_enabled: false
console_ingress_annotations:
