{{ if eq .Values.api.disableBilling false }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-stripe-config
  labels:
    app: api-server
data:
  stripe-config: {{ quote .Values.api.stripe.configYaml }}
{{- end -}}
{{- if eq .Values.mail.provider "mailjet" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-mail-config
  labels:
    app: api-server
data:
  mail-config.yaml: {{ .Values.mail.mailjet.config | toJson | quote }}
{{- end }}
