---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
      annotations:
        checksum/secrets-config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
        name: api-server
        env:
          - name: SESSION_SECRET
            value: "{{ .Values.api.sessionSecret }}"
          - name: FRONT_END_URL
            value: "{{ .Values.frontend.url }}"
          - name: USER_ADMITTANCE
            value: "{{ .Values.api.userAdmittance }}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: token-store-config
{{- if eq .Values.mail.provider "mailjet" }}
          - name: MJ_APIKEY_PUBLIC
            value: "{{ .Values.mail.mailjet.apiKeyPublic }}"
          - name: MJ_APIKEY_PRIVATE
            value: "{{ .Values.mail.mailjet.apiKeyPrivate }}"
{{- end }}
        args:
          - serve
          - --log-level={{ .Values.api.logLevel }}
          - --http-server-endpoint=0.0.0.0:8080
          - --server-http-url={{ .Values.api.url }}
          - --gh-client-id={{ .Values.api.github.clientID }}
          - --gh-client-secret={{ .Values.api.github.clientSecret }}
          - --az-application-id={{ .Values.api.azure.applicationID }}
          - --az-client-secret={{ .Values.api.azure.clientSecret }}
          - --google-application-id={{ .Values.api.google.applicationID }}
          - --google-client-secret={{ .Values.api.google.clientSecret }}
          - --stripe-secret-key={{ .Values.api.stripe.secretKey }}
          - --masterdata-api-hostname={{ .Values.masterdata.hostname }}
          - --masterdata-api-port={{ .Values.masterdata.port }}
          - --masterdata-api-hmac={{ .Values.masterdata.hmac }}
          - --metal-api-url={{ .Values.metal.url }}
          - --metal-api-hmac={{ .Values.metal.hmac }}
          - --redis-addr={{ .Values.tokenStore.addr }}
          - --admin-subjects={{ join "," .Values.api.adminSubjects }}
          - --max-requests-per-minute={{ .Values.api.rateLimit.maxRequestsPerMinute }}
          - --max-unauthenticated-requests-per-minute={{ .Values.api.rateLimit.maxUnauthenticatedRequestsPerMinute }}
{{- if eq .Values.auditing.backend "meili"}}
          - --auditing-meili-enabled={{ if eq .Values.auditing.backend "meili" }}true{{ else }}false{{end}}
          - --auditing-meili-url={{ .Values.auditing.meili.url }}
          - --auditing-meili-api-key={{ .Values.auditing.meili.key }}
          - --auditing-meili-index-interval={{ .Values.auditing.meili.interval }}
          - --auditing-meili-index-prefix={{ .Values.auditing.meili.indexPrefix }}
          - --auditing-meili-index-keep={{ .Values.auditing.meili.keep }}
{{- end}}
{{- if eq .Values.auditing.backend "timescaledb"}}
          - --auditing-timescaledb-enabled={{ if eq .Values.auditing.backend "timescaledb" }}true{{ else }}false{{end}}
          - --auditing-timescaledb-host={{ .Values.auditing.timescaledb.host }}
          - --auditing-timescaledb-port={{ .Values.auditing.timescaledb.port }}
          - --auditing-timescaledb-db={{ .Values.auditing.timescaledb.db }}
          - --auditing-timescaledb-user={{ .Values.auditing.timescaledb.user }}
          - --auditing-timescaledb-password={{ .Values.auditing.timescaledb.password }}
          - --auditing-timescaledb-retention={{ .Values.auditing.timescaledb.retention }}
{{- end}}
{{- if .Values.api.duros.config }}
          - --duros-config-path=/duros/duros-config.yaml
{{- end -}}
{{- if eq .Values.mail.provider "mailjet" }}
          - --mail-provider={{ .Values.mail.provider }}
          - --mail-config-path=/app-config/mail-config.yaml
          - --smtp-from-address={{ .Values.mail.smtpFromAddress }}
          - --smtp-from-name={{ .Values.mail.smtpFromName }}
{{- end -}}
{{- if .Values.gardener.kubeconfig }}
          - --gardener-kubeconfig=/gardener/kubeconfig
{{- else }}
          - --stage=DEV
{{- end }}
{{- if .Values.hubspot.portalID }}
          - --hubspot-portal-id={{ .Values.hubspot.portalID }}
{{- end }}
{{- if .Values.hubspot.formGUID }}
          - --hubspot-form-guid={{ .Values.hubspot.formGUID }}
{{- end }}
{{- if .Values.api.resources }}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: masterdata-api-certs
          mountPath: /certs/
        - name: duros-config
          mountPath: /duros/
{{- if .Values.gardener.kubeconfig }}
        - name: gardener
          mountPath: /gardener/
{{- end }}
{{- if eq .Values.mail.provider "mailjet" }}
        - name: mail-config
          mountPath: /app-config
{{- end }}
      volumes:
        - name: masterdata-api-certs
          secret:
            secretName: masterdata-api-certs
        - name: duros-config
          secret:
            secretName: duros-config
{{- if .Values.gardener.kubeconfig }}
        - name: gardener
          secret:
            secretName: gardener-kubeconfig
{{- end }}
{{- if eq .Values.mail.provider "mailjet" }}
        - name: mail-config
          configMap:
            name: api-server-mail-config
            items:
              - key: mail-config.yaml
                path: mail-config.yaml
{{- end }}
