---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
      annotations:
        checksum/secrets-config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - image: {{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
        name: api-server
        env:
          - name: SESSION_SECRET
            value: "{{  .Values.api.sessionSecret }}"
          - name: FRONT_END_URL
            value: "{{  .Values.frontend.url }}"
          - name: USER_ADMITTANCE
            value: "{{ .Values.api.userAdmittance }}"
        args:
          - serve
          - --log-level={{ .Values.api.logLevel }}
          - --http-server-endpoint=0.0.0.0:8080
          - --server-http-url={{ .Values.api.url }}
          - --gh-client-id={{ .Values.api.github.clientID }}
          - --gh-client-secret={{ .Values.api.github.clientSecret }}
          - --az-application-id={{ .Values.api.azure.applicationID }}
          - --az-client-secret={{ .Values.api.azure.clientSecret }}
          - --stripe-secret-key={{ .Values.api.stripe.secretKey }}
          - --masterdata-api-hostname={{ .Values.masterdata.hostname }}
          - --masterdata-api-port={{ .Values.masterdata.port }}
          - --masterdata-api-hmac={{ .Values.masterdata.hmac }}
          - --metal-api-url={{ .Values.metal.url }}
          - --metal-api-hmac={{ .Values.metal.hmac }}
          - --auditing-url={{ .Values.auditing.url }}
          - --auditing-api-key={{ .Values.auditing.key }}
          - --auditing-enabled={{ if .Values.auditing.url }}true{{ else }}false{{end}}
          - --auditing-index-interval={{ .Values.auditing.interval }}
          - --auditing-index-keep={{ .Values.auditing.keep }}
          - --auditing-index-prefix={{ .Values.auditing.indexPrefix }}
          - --jwt-token-secret={{ .Values.api.jwtTokenSecret }}
{{- if .Values.gardener.kubeconfig }}
          - --gardener-kubeconfig=/gardener/kubeconfig
{{- else }}
          - --stage=DEV
{{- end }}
{{- if .Values.api.resources }}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: masterdata-api-certs
          mountPath: /certs/
{{- if .Values.gardener.kubeconfig }}
        - name: gardener
          mountPath: /gardener/
{{- end }}
      volumes:
        - name: masterdata-api-certs
          secret:
            secretName: masterdata-api-certs
{{- if .Values.gardener.kubeconfig }}
        - name: gardener
          secret:
            secretName: gardener-kubeconfig
{{- end }}
