{{- if .Values.api.hpa.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-serverr
spec:
  maxReplicas: {{ .Values.api.hpa.maxReplicas }}
  minReplicas: {{ .Values.api.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-server
  targetCPUUtilizationPercentage: {{ .Values.api.hpa.cpuPercentage }}
{{- end }}
