{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server-grpc
  annotations:
    # we will always terminate grpc at the api-server
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
{{- if .Values.ingress.annotationsGrpc }}
{{ toYaml .Values.ingress.annotationsGrpc | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.grpcHost }}
  rules:
  - host: {{ .Values.ingress.grpcHost }}
    http:
      paths:
      - backend:
          service:
            name: api-server
            port:
              number: 9090
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server-auth
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
{{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.authHost }}
    secretName: api-server-auth-tls
{{- end }}
  rules:
  - host: {{ .Values.ingress.authHost }}
    http:
      paths:
      - backend:
          service:
            name: api-server
            port:
              number: 8080
        path: /auth
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server-grpc-web
  annotations:
{{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.grpcWebHost }}
    secretName: api-server-grpc-web-tls
{{- end }}
  rules:
  - host: {{ .Values.ingress.grpcWebHost }}
    http:
      paths:
      - backend:
          service:
            name: api-server
            port:
              number: 8080
        path: /
        pathType: Prefix
{{- end }}
