---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-server-setup-stripe
  labels:
    app: api-server
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: api-server
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          env:
            - name: SESSION_SECRET
              value: "{{ .Values.api.sessionSecret }}"
          args:
            - stripe-jobs
            - --log-level={{ .Values.api.logLevel }}
            - --stripe-secret-key={{ .Values.api.stripe.secretKey }}
            - --stripe-config-path=/app-config/stripe-config.yaml
            - setup
          volumeMounts:
            - name: stripe-config
              mountPath: /app-config
      volumes:
        - name: stripe-config
          configMap:
            name: api-server-stripe-config
            items:
              - key: stripe-config
                path: stripe-config.yaml
      restartPolicy: Never

{{- if eq .Values.mail.provider "mailjet" }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-server-send-coupon-usage-warnings
  labels:
    app: api-server
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  schedule: "13 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: api-server
              image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
              env:
                - name: SESSION_SECRET
                  value: "{{ .Values.api.sessionSecret }}"
                - name: MJ_APIKEY_PUBLIC
                  value: "{{ .Values.mail.mailjet.apiKeyPublic }}"
                - name: MJ_APIKEY_PRIVATE
                  value: "{{ .Values.mail.mailjet.apiKeyPublic }}"
              args:
                - stripe-jobs
                - --log-level={{ .Values.api.logLevel }}
                - --stripe-secret-key={{ .Values.api.stripe.secretKey }}
                - --mail-provider={{ .Values.mail.mailProvider }}
                - --mail-config-path=/mail/mail-config.yaml
                - --smtp-from-address={{ .Values.mail.smtpFromAddress }}
                - --smtp-from-name={{ .Values.mail.smtpFromName }}
                - check-for-coupon-usage
              volumeMounts:
              - name: mail-config
                mountPath: /mail
          volumes:
            - name: mail-config
              configMap:
                name: api-server-mail-config
                items:
                  - key: mail-config.yaml
                    path: mail-config.yaml
{{- end -}}