{{- if .Values.api.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cloud-status-dashboard
spec:
  minAvailable: {{- if .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: api-server
{{- end }}
