---
apiVersion: v1
kind: Secret
metadata:
  name: masterdata-api-certs
type: Opaque
data:
  ca.pem: {{ .Values.masterdata.ca | b64enc }}
  client.pem: {{ .Values.masterdata.cert | b64enc }}
  client-key.pem: {{ .Values.masterdata.certKey | b64enc }}
{{- if .Values.api.ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-ca-certs
type: Opaque
data:
  ca.pem: {{ .Values.api.ca | b64enc }}
{{- end }}
{{- if and .Values.api.cert .Values.api.certKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-server-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.api.cert | b64enc }}
  tls.key: {{ .Values.api.certKey | b64enc }}
{{- end }}
{{- if .Values.gardener.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-kubeconfig
type: Opaque
data:
  kubeconfig: {{ .Values.gardener.kubeconfig | b64enc }}
{{- end }}
