---
apiVersion: v1
kind: Secret
metadata:
  name: duros-config
type: Opaque
data:
  duros-config.yaml: {{ .Values.api.duros.config | toJson | b64enc }}
{{- if .Values.gardener.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-kubeconfig
type: Opaque
data:
  kubeconfig: {{ .Values.gardener.kubeconfig | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: token-store-config
type: Opaque
data:
  password: {{ .Values.tokenStore.password | b64enc }}
