---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  selector:
    app: api-server
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
